In [6]:
import torch
print(torch.__version__)

2.7.0


In [16]:
if torch.cuda.is_available():
    print("GPU is aviailable")
    print(f"Using GPU: {tourch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU")

GPU not available. Using CPU


In [34]:
# Creating a Tensor

#using empty
a = torch.empty(2,5)
a

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [26]:
#check type
type(a)

torch.Tensor

In [28]:
#using zeros
torch.zeros(2,5)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [30]:
#using ones
torch.ones(2,5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [40]:
#using rand
torch.rand(2,5)

tensor([[0.0398, 0.7824, 0.5581, 0.5087, 0.9853],
        [0.6379, 0.0082, 0.5777, 0.4265, 0.0506]])

In [48]:
#using manual_seed 
torch.manual_seed(100)
torch.rand(2,5)

tensor([[0.1117, 0.8158, 0.2626, 0.4839, 0.6765],
        [0.7539, 0.2627, 0.0428, 0.2080, 0.1180]])

In [52]:
#using tensor 
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [58]:
#using arange
torch.arange(0,10)
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [62]:
#using linspace
torch.linspace(0,10,3)

tensor([ 0.,  5., 10.])

In [66]:
#using eye
torch.eye(5,5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [72]:
#using full
torch.full((5,5),1)

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])

In [90]:
# find out shape
x = torch.tensor([[1,2],[3,4],[5,6]])
print(x)
print("Shape:",x.shape)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
Shape: torch.Size([3, 2])


In [92]:
torch.empty_like(x)

tensor([[0, 0],
        [0, 0],
        [0, 0]])

In [100]:
torch.zeros_like(x)

tensor([[0, 0],
        [0, 0],
        [0, 0]])

In [102]:
torch.ones_like(x)

tensor([[1, 1],
        [1, 1],
        [1, 1]])

In [112]:
torch.rand_like(x,dtype=torch.float)

tensor([[0.9969, 0.7565],
        [0.2239, 0.3023],
        [0.1784, 0.8238]])

In [2]:
# Mathematical Operations

In [10]:
x = torch.rand(2,2)
x

tensor([[0.0196, 0.6634],
        [0.9844, 0.1838]])

In [52]:
x + 2
x - 2
x * 2
(x * 100) // 3
((x * 100) // 3) % 2
x ** 2

tensor([[3.8598e-04, 4.4011e-01],
        [9.6907e-01, 3.3788e-02]])

In [80]:
#abs

c = torch.tensor([1,-2,-4.57,4.322])
print(torch.abs(c))
print(torch.neg(c))
print(torch.round(c))
print(torch.ceil(c))
print(torch.floor(c))
print(torch.clamp(c,min=-1,max=1))


tensor([1.0000, 2.0000, 4.5700, 4.3220])
tensor([-1.0000,  2.0000,  4.5700, -4.3220])
tensor([ 1., -2., -5.,  4.])
tensor([ 1., -2., -4.,  5.])
tensor([ 1., -2., -5.,  4.])
tensor([ 1., -1., -1.,  1.])


In [174]:
x = torch.randint(size=(2,3),low=1, high=10,dtype=torch.float)
torch.manual_seed(100)

print(x)

print("Sum:",torch.sum(x))
print("Col-sum:",torch.sum(x,dim=0))
print("Row-sum:",torch.sum(x,dim=1))

print("Mean:",torch.mean(x))
print("Col-mean:",torch.mean(x,dim=0))
print("Row-mean:",torch.mean(x,dim=1))

print("Median:",torch.median(x))

print("Max:",torch.max(x))
print("Min:",torch.min(x))

print("Product:",torch.prod(x))
print("Standard Devation:",torch.std(x))
print("Variance:",torch.var(x))

print("Argmax:",torch.argmax(x))
print("Argmin:",torch.argmin(x))


tensor([[8., 8., 9.],
        [9., 2., 8.]])
Sum: tensor(44.)
Col-sum: tensor([17., 10., 17.])
Row-sum: tensor([25., 19.])
Mean: tensor(7.3333)
Col-mean: tensor([8.5000, 5.0000, 8.5000])
Row-mean: tensor([8.3333, 6.3333])
Median: tensor(8.)
Max: tensor(9.)
Min: tensor(2.)
Product: tensor(82944.)
Standard Devation: tensor(2.6583)
Variance: tensor(7.0667)
Argmax: tensor(2)
Argmin: tensor(4)


In [182]:
f = torch.randint(size=(2,3),low=1,high=10)
g = torch.randint(size=(3,2),low=1,high=10)
print(f)
print(g)

tensor([[8, 8, 9],
        [9, 2, 8]])
tensor([[7, 2],
        [7, 3],
        [8, 9]])


In [184]:
x = torch.matmul(f,g)
x

tensor([[184, 121],
        [141,  96]])

In [186]:
torch.cuda.is_available()

False

In [188]:
device = torch.device('cuda')