In [4]:
import numpy as np

In [12]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
arr3 = np.zeros((3,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
arr4 = np.ones((2,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
arr5 = np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
arr6 = np.arange(8)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7])

In [16]:
arr7 = np.arange(12,24)
arr7

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [30]:
arr8 = np.arange(5,100,5)
arr8

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

In [36]:
arr9 = np.linspace(0,10,5)
arr9

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [34]:
arr10 = arr8.copy()
arr10

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

In [36]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
arr1.shape

(10,)

In [40]:
arr2.shape

(2, 3)

In [42]:
arr9 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [44]:
arr9

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [46]:
arr9.shape

(2, 2, 2)

In [48]:
arr9.ndim

3

In [50]:
arr2.ndim

2

In [52]:
arr1.ndim

1

In [54]:
arr1.size

10

In [56]:
arr1.itemsize

8

In [58]:
arr1.dtype

dtype('int64')

In [60]:
arr1.astype('int')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
arr1.dtype

dtype('int64')

In [64]:
l = range(100)
ll = np.arange(100)
ll

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [66]:
import sys

In [68]:
print(sys.getsizeof(1)*len(l))

2800


In [70]:
print(ll.itemsize*ll.size)

800


In [72]:
import time

In [78]:
x = range(100000000)
y = range(100000000,200000000)
start_time=time.time()
c = [x+y for x,y in zip(x,y)]
print(time.time()-start_time)

4.347198009490967


In [80]:
x = np.arange(100000000)
y = np.arange(100000000,200000000)
start_time=time.time()
c = x+y
print(time.time()-start_time)

1.8353090286254883


In [8]:
arr12 = np.arange(24).reshape(6,4)
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [10]:
arr12[:,2]

array([ 2,  6, 10, 14, 18, 22])

In [30]:
arr12[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [36]:
arr12[4:,2:]

array([[18, 19],
       [22, 23]])

In [38]:
for i in arr12:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [40]:
for i in np.nditer(arr12):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [46]:
arr1.transpose()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
arr6.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [64]:
arr13 = np.arange(100,110)
arr13.reshape(2,5)

array([[100, 101, 102, 103, 104],
       [105, 106, 107, 108, 109]])

In [68]:
np.hstack((arr6,arr13))

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9, 100, 101, 102,
       103, 104, 105, 106, 107, 108, 109])

In [70]:
np.vstack((arr6,arr13))

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109]])

In [72]:
a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [76]:
a[[0,2,4]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [94]:
abc = np.random.randint(low=1,high=200,size=15).reshape(5,3)
abc

array([[160, 126,  86],
       [128,  94,  26],
       [169,  23,  57],
       [113, 124,  38],
       [  7, 165,  40]])

In [96]:
abc>100

array([[ True,  True, False],
       [ True, False, False],
       [ True, False, False],
       [ True,  True, False],
       [False,  True, False]])

In [104]:
abc[(abc>100) & (abc%2!=0)]

array([169, 113, 165])

In [110]:
abc[(abc>100) & (abc%2!=0)]=0
abc

array([[160, 126,  86],
       [128,  94,  26],
       [  0,  23,  57],
       [  0, 124,  38],
       [  7,   0,  40]])

In [49]:
x = np.linspace(-40,40,100)
x

array([-40.        , -39.19191919, -38.38383838, -37.57575758,
       -36.76767677, -35.95959596, -35.15151515, -34.34343434,
       -33.53535354, -32.72727273, -31.91919192, -31.11111111,
       -30.3030303 , -29.49494949, -28.68686869, -27.87878788,
       -27.07070707, -26.26262626, -25.45454545, -24.64646465,
       -23.83838384, -23.03030303, -22.22222222, -21.41414141,
       -20.60606061, -19.7979798 , -18.98989899, -18.18181818,
       -17.37373737, -16.56565657, -15.75757576, -14.94949495,
       -14.14141414, -13.33333333, -12.52525253, -11.71717172,
       -10.90909091, -10.1010101 ,  -9.29292929,  -8.48484848,
        -7.67676768,  -6.86868687,  -6.06060606,  -5.25252525,
        -4.44444444,  -3.63636364,  -2.82828283,  -2.02020202,
        -1.21212121,  -0.4040404 ,   0.4040404 ,   1.21212121,
         2.02020202,   2.82828283,   3.63636364,   4.44444444,
         5.25252525,   6.06060606,   6.86868687,   7.67676768,
         8.48484848,   9.29292929,  10.1010101 ,  10.90

In [53]:
y = np.sin(x)
y.size

100

In [55]:
x.size

100

In [57]:
import matplotlib.pyplot as plt
%matplotlib inline

In [59]:
plt.plot(x,y) 

In [ ]:
y=x*x+2

In [61]:
plt.plot(x,y) 

In [85]:
import time
a = time.time()
c = time.time()-a
print(c)
print(a)

-3.504753112792969e-05
1732699088.938698


In [22]:
arr50 = np.arange(20).reshape(5,4)
arr50

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [30]:
arr51 = np.arange(20,40).reshape(5,4)
arr51

array([[20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39]])

In [32]:
np.hstack((arr50,arr51))

array([[ 0,  1,  2,  3, 20, 21, 22, 23],
       [ 4,  5,  6,  7, 24, 25, 26, 27],
       [ 8,  9, 10, 11, 28, 29, 30, 31],
       [12, 13, 14, 15, 32, 33, 34, 35],
       [16, 17, 18, 19, 36, 37, 38, 39]])

In [36]:
np.vstack((arr50,arr51))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39]])

In [42]:
a = np.arange(24,48).reshape(6,4)
a

array([[24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47]])

In [52]:
x = np.linspace(1,100,100)
x

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])